#define PIN_A           2       
#define PIN_B           3       
#define PIN_X           4       
#define PIN_Y           5      
#define PIN_DUP         6     
#define PIN_DDOWN       7    
#define PIN_DLEFT       8   
#define PIN_DRIGHT      9  
#define PIN_START       10  
#define PIN_LTRIGGER    11 
#define PIN_RTRIGGER    14
//#define PIN_CUP         12     
//#define PIN_CDOWN       13   
//#define PIN_CLEFT       14   
//#define PIN_CRIGHT      15  
#define PIN_UP          15      
#define PIN_DOWN        16    
#define PIN_LEFT        17    
#define PIN_RIGHT       18   
#define PIN_ZTRIGGER    19